apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - pvc.yaml
  - seed-nextcloud-appdata.yaml
  - seed-nextcloud-redis.yaml
  - restore-nextcloud-postgres.yaml

commonLabels:
  app.kubernetes.io/name: nextcloud
  app.kubernetes.io/managed-by: argocd
