apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - externalsecret.yaml
  - litellm-configmap.yaml
  - litellm-deployment.yaml
  - litellm-service.yaml
  - litellm-pdb.yaml
  - pvc-llama-models-cache.yaml
  - llama-static-a-configmap.yaml
  - llama-static-a-deployment.yaml
  - llama-static-a-service.yaml
  - llama-static-b-configmap.yaml
  - llama-static-b-deployment.yaml
  - llama-static-b-service.yaml
  - llama-swap-configmap.yaml
  - llama-swap-deployment.yaml
  - llama-swap-service.yaml

commonLabels:
  app.kubernetes.io/name: llama-backend
  app.kubernetes.io/managed-by: argocd
