apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gatewayclass.yaml
  - gateway.yaml
  - certificate-wildcard-k8s-rcrumana-xyz.yaml
  - httproute-http-to-https-redirect.yaml
