apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard
spec:
  replicas: 1
  selector:
    matchLabels: { app: whiteboard }
  template:
    metadata:
      labels: { app: whiteboard }
    spec:
      containers:
        - name: wbo
          image: lovasoa/wbo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5001"
          ports:
            - name: http
              containerPort: 5001
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits:   { cpu: "500m", memory: 512Mi }
