apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - pvc.yaml
  - db-service.yaml
  - db-deployment.yaml
  - externalsecret.yaml
  - unifi-deployment.yaml
  - unifi-service-tcp.yaml
  - unifi-service-udp.yaml

commonLabels:
  app.kubernetes.io/name: unifi-controller
  app.kubernetes.io/managed-by: argocd
