apiVersion: apps/v1
kind: Deployment
metadata:
  name: opnsense-proxy
  labels:
    app: opnsense-proxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: opnsense-proxy
  template:
    metadata:
      labels:
        app: opnsense-proxy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: opnsense-proxy
              topologyKey: kubernetes.io/hostname
      containers:
        - name: tcp-proxy
          image: alpine/socat:1.8.0.3
          imagePullPolicy: IfNotPresent
          args:
            - -dd
            - TCP-LISTEN:8443,fork,reuseaddr
            - TCP:192.168.1.1:4443
          ports:
            - name: https-proxy
              containerPort: 8443
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: https-proxy
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: https-proxy
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi

