apiVersion: v1
kind: Service
metadata:
  name: opnsense-https
  annotations:
    haproxy-ingress.github.io/secure-backends: "true"
    haproxy-ingress.github.io/backend-protocol: "h1-ssl"
spec:
  ports:
    - name: https
      port: 4443
      targetPort: 4443
  type: ClusterIP
