apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
data:
  HOST: "0.0.0.0"
  PORT: "3080"
  APP_TITLE: "LibreChat"
  DOMAIN: "https://chat.rcrumana.xyz"
  OPENAI_API_BASE: "http://llm-gateway.ai.svc.cluster.local:4000/v1"
  SEARCH: "true"
  ALLOW_REGISTRATION: "false"
  ALLOW_SHARED_LINKS: "true"
  RAG_API_URL: "http://librechat-rag-api.ai.svc.cluster.local:8000"
  MEILI_HOST: "http://librechat-meilisearch.ai.svc.cluster.local:7700"
