apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - externalsecret.yaml
  - configmap.yaml
  - librechat-yaml-configmap.yaml
  - librechat-pvc.yaml
  - mongodb-pvc.yaml
  - mongodb-service.yaml
  - mongodb-statefulset.yaml
  - meilisearch-pvc.yaml
  - meilisearch-service.yaml
  - meilisearch-statefulset.yaml
  - rag-api-service.yaml
  - rag-api-deployment.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: librechat
  app.kubernetes.io/managed-by: argocd
