apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: other

resources:
  - service.yaml
  - endpoints.yaml
  - endpointslice.yaml

labels:
  - includeSelectors: false
    includeTemplates: false
    pairs:
      app.kubernetes.io/name: minio
      app.kubernetes.io/managed-by: argocd
