apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - haproxy.yaml
  - restricted-internal.yaml

labels:
- pairs:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: haproxy-ingress
  includeSelectors: false  # Don't add to selectors, only to metadata
