apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-general-config
data:
  VLLM_MODEL: "Qwen/Qwen3-30B-A3B"
  VLLM_SERVED_MODEL_NAME: "qwen3-30b-a3b"
  VLLM_DOWNLOAD_DIR: "/models"
  VLLM_GPU_MEMORY_UTILIZATION: "0.90"
  VLLM_MAX_MODEL_LEN: "8192"
  VLLM_TP_SIZE: "1"
  VLLM_PORT: "8000"
