apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
  - configmap.yaml
  - deployment.yaml
  - service-headless.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: vllm-general
  app.kubernetes.io/managed-by: argocd
