apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-app.yaml
  - cert-manager-extras-app.yaml
  - metallb-app.yaml
  - metallb-config-app.yaml
  - haproxy-app.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
