apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces-app.yaml
  - cert-manager-app.yaml
  - cert-manager-extras-app.yaml
  - vault-app.yaml
  - external-secrets-app.yaml
  - external-secrets-extras-app.yaml
  - egress-qos-app.yaml
  - metallb-app.yaml
  - metallb-config-app.yaml
  - haproxy-app.yaml
  - descheduler-app.yaml
  - vpa-app.yaml
  - linkerd-crds-app.yaml
  - linkerd2-cni-app.yaml
  - linkerd-identity-app.yaml
  - linkerd-control-plane-app.yaml
  - linkerd-viz-app.yaml
  - shared-ingress-app.yaml
  - portfolio-app.yaml
  - portfolio-staging-app.yaml
  - opnsense-app.yaml
  - minio-app.yaml
  - arr-app.yaml
  - arr-lts-app.yaml
  - arr-lts2-app.yaml
  - collabora-app.yaml
  - elasticsearch-app.yaml
  - homarr-app.yaml
  - jellyfin-app.yaml
  - librechat-app.yaml
  - llama-backend-app.yaml
  - immich-app.yaml
  - nextcloud-app.yaml
  - plex-app.yaml
  - headscale-app.yaml
  - truenas-app.yaml
  - unifi-controller-app.yaml
  - uptime-kuma-app.yaml
  - vaultwarden-app.yaml
  - whiteboard-app.yaml
  - rook-ceph-operator-app.yaml
  - rook-ceph-cluster-app.yaml
  - snapshot-controller-app.yaml
  - volsync-app.yaml
  - volsync-replicationsources-app.yaml
  - postgres-operator-app.yaml
  - redis-enterprise-operator-app.yaml
  - redis-platform-app.yaml
  - redis-platform-databases-app.yaml
  - pg-platform-app.yaml
  - pg-media-app.yaml
  - pg-ai-app.yaml
  - pg-productivity-app.yaml
  - pg-other-app.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
