apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces-app.yaml
  - cert-manager-app.yaml
  - cert-manager-extras-app.yaml
  - metallb-app.yaml
  - metallb-config-app.yaml
  - haproxy-app.yaml
  - descheduler-app.yaml
  - linkerd-crds-app.yaml
  - linkerd2-cni-app.yaml
  - linkerd-identity-app.yaml
  - linkerd-control-plane-app.yaml
  - linkerd-viz-app.yaml
  - shared-ingress-app.yaml
  - portfolio-app.yaml
  - portfolio-staging-app.yaml
  - opnsense-app.yaml
  - arr-app.yaml
  - arr-lts-app.yaml
  - arr-lts2-app.yaml
  - jellyfin-app.yaml
  - immich-app.yaml
  - plex-app.yaml
  - truenas-app.yaml
  - rook-ceph-operator-app.yaml
  - rook-ceph-cluster-app.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
