apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-api-app.yaml
  - cert-manager-app.yaml
  - cert-manager-extras-app.yaml
  - metallb-app.yaml
  - metallb-config-app.yaml
  - haproxy-app.yaml
  - shared-ingress-app.yaml
  - rook-ceph-operator-app.yaml
  - rook-ceph-temp-cluster-app.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
