apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-ingress
  namespace: argocd
  annotations:
    # Wait for HAProxy Ingress controller to be installed.
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/rrumana/k8s-homelab-2.git
    targetRevision: main
    path: cluster/apps/shared/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
