apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - ceph-cluster.yaml
  - ceph-block-pool.yaml
  - rook-config-override.yaml
  - storage-class.yaml
  - toolbox.yaml
