apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  config.yaml: |-
    server_url: https://headscale.rcrumana.xyz
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: false

    noise:
      private_key_path: /var/lib/headscale/noise_private.key

    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
      allocation: sequential

    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 3h

    dns:
      magic_dns: true
      base_domain: tail.rcrumana.xyz
      override_local_dns: true
      nameservers:
        global:
          - 1.1.1.1
          - 1.0.0.1
        split:
          rcrumana.xyz:
            - 192.168.1.1
      search_domains: []
      extra_records: []

    database:
      type: postgres
      postgres:
        host: pg-other-rw.databases.svc.cluster.local
        port: 5432
        name: headscale
        user: headscale
        # Password is injected via environment variable HEADSCALE_DATABASE_POSTGRES_PASS
        pass: ""
        max_open_conns: 10
        max_idle_conns: 10
        conn_max_idle_time_secs: 3600
        ssl: false

    log:
      level: info
      format: text

    policy:
      mode: file
      path: /etc/headscale/policy.hujson

    unix_socket: /var/run/headscale/headscale.sock
    unix_socket_permission: "0770"

    disable_check_updates: false
    ephemeral_node_inactivity_timeout: 30m
    randomize_client_port: false
  policy.hujson: |-
    {
      "Groups": {
        "group:admins": ["admin@local"],
        "group:users": ["ryan@local"]
      },
      "AutoApprovers": {
        "Routes": {
          "192.168.1.0/24": ["group:admins"]
        }
      }
    }
