apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: other

resources:
  - configmap.yaml
  - pvc.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - service.yaml
  - deployment.yaml
  - ui-service.yaml
  - ui-deployment.yaml
  - restore-headscale-postgres.yaml

commonLabels:
  app.kubernetes.io/name: headscale
  app.kubernetes.io/managed-by: argocd
