apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: other

resources:
  - externalsecret.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ui-service.yaml
  - ui-deployment.yaml

commonLabels:
  app.kubernetes.io/name: headscale
  app.kubernetes.io/managed-by: argocd
