apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: other

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: truenas
  app.kubernetes.io/managed-by: argocd
