apiVersion: v1
kind: Service
metadata:
  name: truenas-https
  annotations:
    haproxy-ingress.github.io/secure-backends: "true"
    haproxy-ingress.github.io/backend-protocol: "h1-ssl"
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 443

