apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - externalsecret.yaml

commonLabels:
  app.kubernetes.io/name: homarr
  app.kubernetes.io/managed-by: argocd
