apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productivity

resources:
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml

commonLabels:
  app.kubernetes.io/name: homarr
  app.kubernetes.io/managed-by: argocd
