apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - externalsecret.yaml
  - postgres-configmap.yaml
  - pvc.yaml
  - pf-sync-configmap.yaml
  - deployment.yaml
  - service.yaml
  - vpa.yaml

commonLabels:
  app.kubernetes.io/name: arr
  app.kubernetes.io/managed-by: argocd
