apiVersion: v1
kind: ConfigMap
metadata:
  name: arr-postgres-config
  labels:
    app: arr-stack
data:
  JELLYSEERR_DB_HOST: "10.45.245.79"
  JELLYSEERR_DB_PORT: "5432"
  JELLYSEERR_DB_USER: "jellyseerr"
  JELLYSEERR_DB_NAME: "jellyseerr"
