apiVersion: v1
kind: Service
metadata:
  name: qbit
  labels: { app: arr-stack }
spec:
  type: ClusterIP
  selector: { app: arr-stack }
  ports:
    - name: http
      port: 80
      targetPort: 8020
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels: { app: arr-stack }
spec:
  type: ClusterIP
  selector: { app: arr-stack }
  ports:
    - name: http
      port: 80
      targetPort: 8989
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels: { app: arr-stack }
spec:
  type: ClusterIP
  selector: { app: arr-stack }
  ports:
    - name: http
      port: 80
      targetPort: 7878
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  labels: { app: arr-stack }
spec:
  type: ClusterIP
  selector: { app: arr-stack }
  ports:
    - name: http
      port: 80
      targetPort: 8686
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels: { app: arr-stack }
spec:
  type: ClusterIP
  selector: { app: arr-stack }
  ports:
    - name: http
      port: 80
      targetPort: 9696
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels: { app: arr-stack }
spec:
  type: ClusterIP
  selector: { app: arr-stack }
  ports:
    - name: http
      port: 80
      targetPort: 5055
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  labels: { app: arr-stack }
spec:
  type: ClusterIP
  selector: { app: arr-stack }
  ports:
    - name: http
      port: 80
      targetPort: 8191
      protocol: TCP
