apiVersion: v1
kind: Service
metadata:
  name: qbit-lts
  labels: { app: arr-lts }
spec:
  type: ClusterIP
  selector: { app: arr-lts }
  ports:
    - name: http
      port: 80
      targetPort: 8021
      protocol: TCP
