apiVersion: v1
kind: Service
metadata:
  name: portfolio-staging
  labels:
    app: portfolio-staging
spec:
  type: ClusterIP
  selector:
    app: portfolio-staging
  ports:
    - name: http
      port: 80
      targetPort: 8085
      protocol: TCP

