apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  labels: { app: collabora }
spec:
  replicas: 1
  selector:
    matchLabels: { app: collabora }
  template:
    metadata:
      labels: { app: collabora }
    spec:
      containers:
        - name: collabora
          image: collabora/code:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: domain
              value: "nextcloud\\.k8s\\.rcrumana\\.xyz"
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true --o:server_name=collabora.k8s.rcrumana.xyz"
          ports:
            - name: http
              containerPort: 9980
          readinessProbe:
            tcpSocket: { port: 9980 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 9980 }
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests: { cpu: 200m, memory: 1Gi }
            limits:   { cpu: "2", memory: 3Gi }
