apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: other

resources:
  - pvc.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: ceph-smoke
  app.kubernetes.io/managed-by: argocd
