apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gatewayclasses.yaml
  - gateways.yaml
  - httproutes.yaml
  - referencegrants.yaml
  - tcproutes.yaml
  - tlsroutes.yaml
