apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  labels:
    app: immich
data:
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  NODE_ENV: "production"
  LOG_LEVEL: "log"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
