apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: scheduling
  labels:
    app.kubernetes.io/name: vpa-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vpa-recommender
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      containers:
        - name: recommender
          image: registry.k8s.io/autoscaling/vpa-recommender:1.6.0
          imagePullPolicy: IfNotPresent
          args:
            - --v=4
            - --stderrthreshold=info
            - --pod-recommendation-min-cpu-millicores=15
            - --pod-recommendation-min-memory-mb=100
            - --storage=checkpoint
            - --checkpoints-gc-interval=1h
            - --kube-api-qps=100
            - --kube-api-burst=100
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
